# Generated by Django 3.1.6 on 2021-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
    ]
