# Generated by Django 3.1.6 on 2021-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
